# Generated by Django 2.1.7 on 2019-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crn',
            name='cr_cash',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
