# Generated by Django 2.1.7 on 2019-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_note', '0004_remove_crn_amount_in_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crn',
            name='cr_status',
            field=models.CharField(default='Delivered', max_length=1000),
        ),
    ]
