# Generated by Django 2.1.7 on 2019-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_note', '0005_auto_20190409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crn',
            name='cr_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
